application: smart-sweeper
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static


- url: /test
  script: test.py

- url: /deltest
  script: test_delete.py

- url: /.*
  script: main.py
